

export enum ScreenRoutes {

    HOME = "HOME",
    INCOMES = "INCOMES",
    INCOMES_CREATE = "INCOMES_CREATE",

    BUDGET_EXPENSES = "BUDGET_EXPENSES",

    EXPENSES = "EXPENSES",
    EXPENSES_CREATE = "EXPENSES_CREATE",

    BUDGETS = "BUDGETS",
    BUDGETS_CREATE= "BUDGETS_CREATE",
}

export enum NavigatorRoutes {
    HOME = "HOME_NAVIGATOR",
}


