

export enum ScreenRoutes {

    HOME = "HOME",
    INCOMES = "INCOMES",
    INCOMES_CREATE = "INCOMES_CREATE",

    BUDGET_EXPENSES = "BUDGET_EXPENSES",

    EXPENSE = "EXPENSE",
    EXPENSES_CREATE = "EXPENSES_CREATE",

    BUDGET = "BUDGET",
    BUDGETS_CREATE= "BUDGETS_CREATE",
}

export enum NavigatorRoutes {
    HOME = "HOME_NAVIGATOR",
}


